package test

import "github.com/stretchr/testify/mock"

type Datastore interface {
	RetrieveValue() string
}

type Database struct{}

func (self *Database) RetrieveValue() string {
	return "invalid"
}

// Datastore is an autogenerated mock type for the Datastore type
type MockDatastore struct {
	mock.Mock
}

// RetreiveValue provides a mock function with given fields:
func (_m *MockDatastore) RetrieveValue() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		// nolint:forcetypeassert // reason: generated code
		r0 = ret.Get(0).(string)
	}

	return r0
}
